# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v4-checkout-{{ .Branch }}-{{ .Revision }}

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Branch }}
            - v1-code-
      - checkout
      - save_cache:
          paths:
            - .
          key: v1-code-{{ .Branch }}

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Branch }}
            - v1-code-

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-code-{{ .Branch }}
            - v1-code-
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: mkdir .tmp && yarn test > .tmp/coverage.xml
      - persist_to_workspace:
          root: .tmp
          paths:
            - coverage.xml
  code_analysis:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .tmp
      - run: cat .tmp/coverage.xml

workflows:
  version: 2
  gdg-worflow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
      - checkout_code:
          requires:
            - test
