version: 2

references:
  image_name: &image_name organization-name/project-name

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run build"
  tests:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run tests"
  release:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: echo "run release"
      - run: bash scripts/release.sh $CIRCLE_BRANCH

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: echo "run deploy"
      - run: bash scripts/deploy.sh $CIRCLE_BRANCH

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
      - tests:
          requires:
            - build
      - release:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
                - staging
                # - lab
      - deploy:
          requires:
            - release
          filters:
            branches:
              only:
                - staging
                # - lab 
  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/