version: 2

references:
  image_name: &image_name organization-name/project-name

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run build"
  tests:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run tests"
  release-staging:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run release-staging"
  release-master:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run release-master"
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo "run deploy $CIRCLE_BRANCH"

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
      - tests:
          requires:
            - build
      - release-staging:
          requires:
            - tests
          filters:
            branches:
              only:
                - staging
      - release-master:
          requires:
            - tests
          filters:
            branches:
              only:
                - master
  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/